# Generated by Django 4.2.14 on 2024-07-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Chat',
        ),
    ]
